name: Build and Deploy

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o ~/discraft

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: discraftbin
        path: ~/discraft
        retention-days: 2
        if-no-files-found: error

  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      KEY: ${{ secrets.DEPOIS_DIZ_ME_O_NOME }}
    steps:
    - name: Set Key
      run: mkdir ~/.ssh && echo "${{env.KEY}}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa 
    - name: Stop Service
      run: ssh -o StrictHostKeyChecking=accept-new -p 500 discraft@minecraft.sneakyrogue.red 'systemctl --user stop discraft.service'
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: discraftbin
        path: ~/
    - name: Upload
      run: "scp -P 500 ~/discraft discraft@minecraft.sneakyrogue.red:"
    - name: Restart Service
      run: ssh -p 500 discraft@minecraft.sneakyrogue.red 'systemctl --user start discraft.service'